version: 2.0
jobs:
  build_resume:
    docker:
      - image: circleci/python:2.7.15-stretch-browsers
    working_directory: ~/resume
    steps:
      - checkout
      - run: 
          name: Build Resume
          command: | 
            sudo make requirements
            make            
      - run:
          name: Spellcheck Resume
          command: |
            sudo apt-get update && sudo apt-get install -y aspell
      - persist_to_workspace:
          root: ~/resume
          paths:
            - dist/*
  build_resume_pandoc:
    docker:
      - image: pandoc/latex:latest
    working_directory: ~/resume
    steps:
      - checkout
      - run: 
          name: Build Resume Pandoc Simple
          command: | 
            apk update && apk add texlive-full
            apk add make openssh git openssh-client
            make pandoc_resume_simple            
      - persist_to_workspace:
          root: ~/resume
          paths:
            - dist/*

  release_resume:
    docker:
      - image: circleci/golang:1.10
    working_directory: ~/resume
    steps: 
      - attach_workspace:
          at: ~/resume
      - run: 
          name: Release Resume
          command: | 
            rm dist/main.css
            go get -u github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} \
              -u ${CIRCLE_PROJECT_USERNAME} \
              -r ${CIRCLE_PROJECT_REPONAME} \
              -c ${CIRCLE_SHA1} \
              -delete ${CIRCLE_TAG} \
              ./dist

workflows:
  version: 2
  build_and_release:
    jobs:
      - build_resume:
          filters:
            tags:
              only: /.*/
      - build_resume_pandoc:
          filters:
            tags:
              only: /.*/
      - release_resume:
          requires:
            - build_resume
            - build_resume_pandoc
          filters:
            tags:
              only: /v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)/
            branches:
              ignore: /.*/
